#!/usr/bin/env python3
"""Build a bounded EPLB plan from the captured EP8 expert-load trace.

The plan is diagnostic only: it is generated by the public EPLB algorithm and
is not installed into vLLM.  We use the aggregate logical-expert counts from
the validated KEEP capture, then estimate the post-replication rank load by
splitting each logical expert's load over its EPLB replicas.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import torch
import csv


def load_weight(csv_path: Path) -> np.ndarray:
    out = np.zeros((48, 128), dtype=np.float64)
    with csv_path.open(newline="", encoding="utf-8") as stream:
        rows = csv.DictReader(stream)
        for row in rows:
            layer = int(row["layer"])
            hist = json.loads(row["expert_histograms"])
            for ep, vals in hist.items():
                ep_i = int(ep)
                for local, count in enumerate(vals):
                    out[layer, ep_i * 16 + local] += float(count)
    return out


def plan_for(weight: np.ndarray, replicas: int) -> dict:
    import sys
    sys.path.insert(0, "/tmp/eplb-ref")
    import eplb  # type: ignore

    phy2log, log2phy, logcnt = eplb.rebalance_experts(
        torch.from_numpy(weight.astype(np.float32)),
        num_replicas=replicas,
        num_groups=1,
        num_nodes=1,
        num_gpus=8,
    )
    phy2log_np = phy2log.cpu().numpy().astype(int)
    logcnt_np = logcnt.cpu().numpy().astype(int)
    rank_width = replicas // 8
    baseline = weight.reshape(48, 8, 16).sum(axis=2)
    pred = np.zeros((48, 8), dtype=np.float64)
    for layer in range(weight.shape[0]):
        for phy in range(replicas):
            logical = int(phy2log_np[layer, phy])
            cnt = max(int(logcnt_np[layer, logical]), 1)
            pred[layer, phy // rank_width] += weight[layer, logical] / cnt
    base_max = baseline.max(axis=1)
    pred_max = pred.max(axis=1)
    base_ratio = base_max / np.maximum(baseline.mean(axis=1), 1e-9)
    pred_ratio = pred_max / np.maximum(pred.mean(axis=1), 1e-9)
    return {
        "num_replicas": replicas,
        "num_gpus": 8,
        "physical_experts_per_gpu": rank_width,
        "algorithm": "deepseek-ai/EPLB.rebalance_experts",
        "input_shape": list(weight.shape),
        "physical_to_logical_map": phy2log_np.tolist(),
        "logical_replica_count": logcnt_np.tolist(),
        "baseline_rank_load": baseline.tolist(),
        "predicted_rank_load": pred.tolist(),
        "baseline_rank_ratio_by_layer": base_ratio.tolist(),
        "predicted_rank_ratio_by_layer": pred_ratio.tolist(),
        "median_baseline_rank_ratio": float(np.median(base_ratio)),
        "median_predicted_rank_ratio": float(np.median(pred_ratio)),
        "median_ratio_reduction": float(1 - np.median(pred_ratio / np.maximum(base_ratio, 1e-9))),
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", type=Path, required=True)
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args()
    weight = load_weight(args.csv)
    result = {
        "source": str(args.csv),
        "model": "Qwen3-30B-A3B",
        "experts": 128,
        "ep": 8,
        "aggregate": {
            "layers": int(weight.shape[0]),
            "total_assignments": float(weight.sum()),
            "per_layer_weight_sum_min": float(weight.sum(axis=1).min()),
            "per_layer_weight_sum_max": float(weight.sum(axis=1).max()),
        },
        "plans": {"EPLB_SMALL": plan_for(weight, 136), "EPLB_LARGE": plan_for(weight, 144)},
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps({k: {x: v[x] for x in ["median_baseline_rank_ratio", "median_predicted_rank_ratio", "median_ratio_reduction"]} for k, v in result["plans"].items()}, indent=2))


if __name__ == "__main__":
    main()
